version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: blog-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  blogapi:
    build: .
    container_name: blog-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
