spring.application.name=connectData
spring.data.mongodb.uri=mongodb://localhost:27017/mydb 
#truy cập vào bên trong server với collection là mydb (nếu chưa có thì sẽ tự động tạo collection có tên là mydb)

# Ứng dụng sẽ chạy trên cổng 8080.
server.port=8080 


# spring.data.mongodb.database=${env.MONGO_DATABASE}
# spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}
