# spring.data.mongodb.uri=mongodb://localhost:27017/blogdb

spring.data.mongodb.database=${env.MONGO_DATABASE}
spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}

# Gi?i h?n kích th??c t?i ?a cho 1 file
spring.servlet.multipart.max-file-size=50MB

# Gi?i h?n t?ng dung l??ng request (nhi?u file)
spring.servlet.multipart.max-request-size=100MB
